<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "access_control"
 *
 * Auto generated by Extension Builder 2014-05-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Access Control',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Nico de Haen',
	'author_email' => 'mail@ndh-websolutions.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.9',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.1.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);